
services:

  web:
    build: .
    container_name: visitor-counter-api

    ports:
      - "5000:5000"

    depends_on:
      - redis

    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:alpine

    container_name: redis-db

    ports:
      - "6379:6379"